### ISSUE TITLE
No mention of `sap.ui.Global` in the API reference

### ISSUE THREAD

**Issue by pubmikeb** [SAP/openui5-docs#64] opened 2021-11-13 16:18 UTC
In the [JavaScript Code Issues](https://openui5nightly.hana.ondemand.com/topic/030fcd14963048218488048f407f8f34) is written:

> _Commonly used names (However they can also be used as AMD references via `sap/ui/Global`)_

However, when I try to check an API reference of [`sap/ui/Global`](https://openui5nightly.hana.ondemand.com/api/module:sap/ui/Global) or [`sap.ui.Global`](https://openui5nightly.hana.ondemand.com/api/module:sap.ui.Global), I get «Not found».

**Comment by flovogt** [comment] 2022-01-25 09:33
Duplicate of https://github.com/SAP/openui5/issues/3384.

**Closed by flovogt** 2022-01-25 09:33 UTC
