### ISSUE TITLE
Typo/missing comma in Step 1 TypeScript Tutorial

### ISSUE THREAD

**Issue by kevinXmichael** [SAP/openui5-docs#95] opened 2024-09-21 11:13 UTC
- Comma is missing after `"id": "ui5.walkthrough"`
- https://github.com/SAP/openui5-docs/blob/main/docs/Step_1_Hello_World_TypeScript_c20489e.md
- <img width="399" alt="Screenshot 2024-09-21 at 13 12 00" src="https://github.com/user-attachments/assets/542994e5-9daf-4a66-b36a-4de454cd17ff">

**Comment by OlMue** [comment] 2024-09-23 06:09
Hi @kevinXmichael, thanks, we'll fix this!

**Comment by KlattG** [comment] 2024-09-23 09:00
Duplicate of https://github.com/SAP-docs/sapui5/pull/156

**Closed by KlattG** 2024-09-23 09:00 UTC

**Comment by KlattG** [comment] 2024-09-23 09:03
Hi @kevinXmichael , the issue has been fixed already; the fix will be implemented with the next UI5 version.
